services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: flask_db
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_HOST: 0.0.0.0
    ports:
      - "3306:3306"
    volumes:
          - ./db_dump/init.sql:/docker-entrypoint-initdb.d/init.sql
